# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=30)),
                ('club_bio', models.CharField(max_length=250)),
                ('club_contact', models.CharField(max_length=250)),
                ('club_meeting', models.CharField(max_length=250)),
                ('club_event', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=30)),
                ('school_code', models.CharField(max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='club_school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.School'),
        ),
    ]
